# default.yml controls global settings and policies/queries that run on all hosts ("All teams").

policies:
queries:
agent_options:
controls:
org_settings:
  fleet_desktop:
    transparency_url: https://catoftheday.com
  host_expiry_settings:
    host_expiry_enabled: true
    host_expiry_window: 30
  server_settings:
    server_url: $FLEET_URL
  org_info:
    org_name: WSK Enterprises
  webhook_settings:
    activities_webhook:
        enable_activities_webhook: true
        destination_url: google.com
  secrets:
    - secret: "REPLACE_WITH_ENVIRONMENT_VARIABLE"
